name: CLA
on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  check_for_CLA:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
   # if: ${{ github.ref_name == 'test-40' }}
    steps:
      - uses: actions/checkout@v3
      - name: install node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: install npm packages
        run: npm install
      - name: run script
        run: node .github/scripts/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}