name: CLA
on:
  workflow_dispatch:
  pull_request:

jobs:
  check_for_CLA:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: github.ref != 'refs/heads/main'  
    steps:
      - uses: actions/checkout@v3
      - name: print stuff
        run: echo "${github.ref_name} github.ref_name" github.ref_name
      - name: install node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: install npm packages
        run: npm install
      - name: run script
        run: node .github/scripts/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}